//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uTikDownloadHelper.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("uTikDownloadHelper.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer this question.
        /// </summary>
        internal static string AnswerThisQuestion {
            get {
                return ResourceManager.GetString("AnswerThisQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the incomplete files?.
        /// </summary>
        internal static string DeleteIncompleteFilesQuestion {
            get {
                return ResourceManager.GetString("DeleteIncompleteFilesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads completed successfully..
        /// </summary>
        internal static string DownloadsCompletedSuccessfully {
            get {
                return ResourceManager.GetString("DownloadsCompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads in Progress.
        /// </summary>
        internal static string DownloadsInProgress {
            get {
                return ResourceManager.GetString("DownloadsInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently downloads in progress, do you want to cancel them?.
        /// </summary>
        internal static string DownloadsInProgressCancelQuestion {
            get {
                return ResourceManager.GetString("DownloadsInProgressCancelQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following title encountered an erorr:.
        /// </summary>
        internal static string FollowingTitleEnounteredAnError {
            get {
                return ResourceManager.GetString("FollowingTitleEnounteredAnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following titles encountered an erorr:.
        /// </summary>
        internal static string FollowingTitlesEncounteredAnErorr {
            get {
                return ResourceManager.GetString("FollowingTitlesEncounteredAnErorr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete Files.
        /// </summary>
        internal static string IncompleteFiles {
            get {
                return ResourceManager.GetString("IncompleteFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just type the hostname, e.g: abc.xyz.com.
        /// </summary>
        internal static string JustTypeTheHostname {
            get {
                return ResourceManager.GetString("JustTypeTheHostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair Failed.
        /// </summary>
        internal static string RepairFailed {
            get {
                return ResourceManager.GetString("RepairFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Wii U Title Key Database.
        /// </summary>
        internal static string TitleKeyWebsiteName {
            get {
                return ResourceManager.GetString("TitleKeyWebsiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to contact the title key website..
        /// </summary>
        internal static string UnableToContactKeyWebsite {
            get {
                return ResourceManager.GetString("UnableToContactKeyWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are currently viewing data that was cached the last time the app was run..
        /// </summary>
        internal static string ViewingCachedData {
            get {
                return ResourceManager.GetString("ViewingCachedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the address of this website?.
        /// </summary>
        internal static string WhatIsTheAddress {
            get {
                return ResourceManager.GetString("WhatIsTheAddress", resourceCulture);
            }
        }
    }
}
